from functools import lru_cache
from typing import Literal
from urllib.parse import urlsplit

from pydantic import Field, SecretStr, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Application configuration loaded from environment variables or ``.env``."""

    database_url: str = Field(description="Async PostgreSQL connection URL")

    # Optional infrastructure integrations used by later project stages.
    rabbitmq_url: str | None = Field(default=None, description="RabbitMQ broker URL")
    redis_url: str | None = Field(default=None, description="Redis connection URL")

    # Optional Telegram integration.
    telegram_api_id: int | None = Field(default=None, description="Telegram application ID")
    telegram_api_hash: SecretStr | None = Field(
        default=None,
        description="Telegram application hash",
    )
    telegram_session_name: str = Field(default="aibot", description="Telegram session name")
    telegram_target_channel: str | None = Field(
        default=None,
        description="Telegram channel used for publishing",
    )
    telegram_publisher: Literal["telethon", "bot"] = Field(
        default="telethon",
        description="Telegram publication backend",
    )
    telegram_bot_token: SecretStr | None = Field(
        default=None,
        description="Telegram Bot API token",
    )
    telegram_target_chat_id: str | None = Field(
        default=None,
        description="Telegram Bot API target chat or private channel ID",
    )

    # Optional OpenAI integration.
    ai_provider: Literal["openai", "ollama"] = Field(
        default="openai",
        description="AI generation backend",
    )
    openai_api_key: SecretStr | None = Field(default=None, description="OpenAI API key")
    openai_model: str = Field(default="gpt-4o-mini", description="OpenAI model name")
    openai_max_tokens: int = Field(
        default=300,
        ge=50,
        le=4000,
        description="Maximum number of output tokens",
    )

    # Optional local Ollama integration.
    ollama_base_url: str = Field(
        default="http://localhost:11434",
        description="Base URL of the Ollama HTTP API",
    )
    ollama_model: str = Field(default="gemma4:e4b", description="Ollama model name")
    ollama_timeout: float = Field(
        default=120.0,
        gt=0,
        le=600,
        description="Ollama request timeout in seconds",
    )

    # News collection settings.
    parse_interval: int = Field(
        default=30,
        ge=1,
        description="Interval between collection runs in minutes",
    )
    max_news_per_source: int = Field(
        default=10,
        ge=1,
        le=100,
        description="Maximum news items collected from one source per run",
    )

    # Automatic pipeline settings.
    auto_publish: bool = Field(
        default=False,
        description="Publish successfully generated pipeline posts automatically",
    )
    pipeline_max_posts_per_run: int = Field(
        default=2,
        ge=1,
        le=10,
        description="Maximum posts generated by one pipeline run",
    )
    pipeline_news_per_post: int = Field(
        default=5,
        ge=1,
        le=10,
        description="Maximum news items grouped into one generated post",
    )

    # Application settings.
    app_env: Literal["dev", "test", "prod"] = Field(
        default="dev",
        description="Application environment",
    )
    log_level: str = Field(default="INFO")
    app_name: str = Field(default="aibot")

    @field_validator("database_url")
    @classmethod
    def validate_database_url(cls, value: str) -> str:
        if not value.startswith("postgresql+asyncpg://"):
            raise ValueError("DATABASE_URL must use the postgresql+asyncpg:// scheme")
        return value

    @field_validator("telegram_api_id", mode="before")
    @classmethod
    def empty_optional_integer_is_none(cls, value: object) -> object:
        """Allow Compose to pass an unset optional numeric integration value."""
        return None if value == "" else value

    @field_validator("telegram_bot_token", "telegram_target_chat_id", mode="before")
    @classmethod
    def empty_optional_value_is_none(cls, value: object) -> object:
        """Allow Compose to pass unset optional Bot API values."""
        return None if value == "" else value

    @field_validator("ollama_base_url")
    @classmethod
    def validate_ollama_base_url(cls, value: str) -> str:
        normalized = value.rstrip("/")
        parsed = urlsplit(normalized)
        if parsed.scheme not in {"http", "https"} or not parsed.netloc:
            raise ValueError("OLLAMA_BASE_URL must use the http:// or https:// scheme")
        return normalized

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )


@lru_cache
def get_settings() -> Settings:
    return Settings()


settings = get_settings()
